# Generated by Django 4.1.7 on 2023-03-12 15:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.functions.text
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lesson Name')),
                ('price_per_hour_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('price_per_hour', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('25'), default_currency='EUR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator({'EUR': 25, 'GBP': 20}), djmoney.models.validators.MaxMoneyValidator({'EUR': 2500, 'GBP': 2000})])),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('max_pupils', models.IntegerField(verbose_name='Max Pupils')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('language_taught', models.CharField(max_length=75, verbose_name='Language Taught')),
                ('lesson', models.ManyToManyField(blank=True, related_name='lesson_teachers', related_query_name='lesson_teacher', to='bookings.lesson', verbose_name='Lessons')),
                ('location', models.ManyToManyField(related_name='location_teachers', related_query_name='location_teacher', to='bookings.location', verbose_name='Locations')),
            ],
            options={
                'ordering': ['last_name', 'middle_name', 'first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name'], name='bookings_te_last_na_e53b51_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['-last_name'], name='desc_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('last_name'), descending=True), name='lower_last_name_idx'),
        ),
    ]
