# Generated by Django 4.1.7 on 2023-03-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lesson Name')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('max_pupils', models.IntegerField(verbose_name='Max Pupils')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=75, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('language_taught', models.CharField(max_length=75, verbose_name='Language Taught')),
            ],
        ),
    ]
