# Generated by Django 4.1.7 on 2023-03-11 13:29

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price_per_hour',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('25'), default_currency='EUR', max_digits=19, validators=[djmoney.models.validators.MinMoneyValidator({'EUR': 25, 'GBP': 20}), djmoney.models.validators.MaxMoneyValidator({'EUR': 2500, 'GBP': 2000})]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price_per_hour_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lesson',
            field=models.ManyToManyField(blank=True, related_name='lesson_teachers', related_query_name='lesson_teacher', to='bookings.lesson', verbose_name='Lessons'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.ManyToManyField(related_name='location_teachers', related_query_name='location_teacher', to='bookings.location', verbose_name='Locations'),
        ),
    ]
