# Generated by Django 4.1.7 on 2023-03-11 23:42

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_lesson_price_per_hour_lesson_price_per_hour_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'middle_name', 'first_name']},
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['last_name'], name='bookings_te_last_na_e53b51_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['-last_name'], name='desc_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(models.OrderBy(django.db.models.functions.text.Lower('last_name'), descending=True), name='lower_last_name_idx'),
        ),
    ]
